//app/layout.js

import "../globals.css"; 
import { NextIntlClientProvider, useMessages } from "next-intl";

export const metadata = { 
  title: "Create Next App", 
  description: "Generated by create next app", 
};

export default function RootLayout({ children , locale }) { 
  const messages = useMessages();
  console.log("locale in RootLayout:", locale);

  return ( 
    <html lang={locale}> 
      <head> 
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" /> 
      </head> 
      <body> 
        <NextIntlClientProvider locale={locale} messages={messages}> 
          {children} 
        </NextIntlClientProvider>
      </body> 
    </html> 
  ); 
}